# Generated by Django 5.0.7 on 2024-08-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('is_working', models.BooleanField(default=False)),
            ],
        ),
    ]
