# Generated by Django 5.0.7 on 2024-08-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_remove_emp_is_working_emp_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('testimonial', models.TextField()),
                ('img', models.ImageField(upload_to='testimonial')),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
