# Generated by Django 5.0.7 on 2024-08-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_testimonial_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
